### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by juanbraga** [justinsalamon/melosynth#1]
Hi Justin,

I am having a try in your melosynth python module on a Ubuntu 14.03 32bits, with python 2.7 Anaconda distribution. When running the code to synthesize a .csv exported from Sonic Visualizer with Melodia it gives me:

Traceback (most recent call last):
  File "melosynth.py", line 399, in <module>
    args.square, args.useneg)
  File "melosynth.py", line 345, in melosynth
    signal.extend(samples)
MemoryError

Any idea on whats going on?

Thanks in advance

**Comment by justinsalamon** [comment]
@juanbraga looks like you're running out of memory. How long is the audio file you analyzed in SV? Also, are you using the default sampling rate (16000) or are you setting different one?

**Comment by juanbraga** [comment]
I am running it with default settings. 

The .csv is generated using Melodia Vamp Plugin from an excerpt of Allemande BWV 1013. It is around 20 seconds long.

**Comment by justinsalamon** [comment]
Then I don't see why you'd run out of memory. Please provide a dropbox/drive link to a folder with the audio file and the CSV file and I'll have a look.

**Comment by juanbraga** [comment]
There you go: https://www.dropbox.com/sh/acmpnk4o4kor7ux/AADoKOVWTt9Ga0Ha-NtBxuS_a?dl=0

Thanks for you time!

**Comment by juanbraga** [comment]
I was exporting wrong the annotation layer! Sorry about that!

The thing was, I made the same mistake twice, in different computers and I was convinced something else wasn't working well.

My mistake! Regards

**Comment by justinsalamon** [comment]
So you've resolved the problem?

**Comment by juanbraga** [comment]
Yes! 
Thanks for sharing your code.

**Comment by justinsalamon** [comment]
Cool :+1:
